title: "Pietro Caforio"
description: "PhD Student in Computer Science — Extreme Multi-Label Classification"
baseurl: ""   # keep empty for user site
url: "https://PietroCaforio.github.io"

# Use a remote theme so GH builds everything (no local Ruby needed)
remote_theme: "pages-themes/hacker@v0.2.0"
plugins: [jekyll-include-cache, jekyll-feed, jekyll-seo-tag, jekyll-remote-theme]


# Navigation (appears as links)
header_pages:
  - about.md
  - blog/index.md

# Math/Code options
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Author
author:
  name: "Pietro Caforio"
  email: "you@example.com"

# Social (optional, helps SEO)
github_username: PietroCaforio
linkedin: pietro-caforio
