title: "Pietro Caforio"
description: "PhD student in Computer Science — Extreme Multi-Label Classification (XMLC)"
url: "https://pietrocaforio.github.io"   # <-- change if you’ll use a custom domain
baseurl: ""                              # keep empty for user site

# Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mint"  # teal-ish skin; you can change later

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:categories/:title/
paginate: 5
paginate_path: /blog/page:num/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Author profile (shown on Home)
author:
  name: "Pietro Caforio"
  avatar: "/assets/images/pietro.jpg"  # <-- put your image here
  bio: "PhD student @ eXascale Infolab (Univ. of Fribourg). Research: Extreme Multi-Label Classification (XMLC)."
  location: "Fribourg, Switzerland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PietroCaforio"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pietro-caforio/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0006-1702-2646"
    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "/assets/cv/Pietro-Caforio-CV.pdf"
    #- label: "Google Scholar"
    #  icon: "ai ai-google-scholar"
    #  url: "https://scholar.google.com/"  


# Defaults (nice MM layouts)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      read_time: true
      share: false
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide

# Collections (optional; you can add later)
# collections:
#   projects:
#     output: true

# SEO/social

feed:
  path: feed.xml
